# Generated by Django 3.0.6 on 2020-06-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200602_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer_ID',
            new_name='customer',
        ),
    ]
